# Generated by Django 5.2 on 2026-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_enrollment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="state",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("enrolled", "Enrolled"),
                    ("rejected", "Rejected"),
                ],
                default="Enrolled",
                max_length=100,
            ),
        ),
    ]
